name: Update ranges
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  compute-ranges:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v2
      
      - id: python
        uses: actions/setup-python@v3.0.0
        with:
          python-version: '3.9'
          cache: 'pip'

      - id: pip    
        run: pip install -r requirements.txt

      - id: run
        run: python main.py

      - id: artifact
        uses: actions/upload-artifact@v3
        with:
          name: ranges
          path: ranges.txt

  upload-file:
    needs: compute-ranges
    runs-on: ubuntu-latest
    steps:
      - id: auth
        uses: google-github-actions/auth@v0.6.0
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - id: download
        uses: actions/download-artifact@v3
        with:
          name: ranges

      - id: rename
        run: mv ranges.txt googleapis.txt

      - id: upload-file
        uses: google-github-actions/upload-cloud-storage@v0.5.0
        with:
          path: googleapis.txt
          destination: '${{ secrets.BUCKET }}'
          parent: false
